### ISSUE TITLE
SteamGuard confirmation error

### ISSUE THREAD

**Issue by camillo1990** [LinarSharifullin/steamcom#7]
Hello! Who had a similar story?
Error when attempting to confirm a sell order placement

Traceback (most recent call last):
  File "C:\Users\win\OneDrive\Рабочий стол\Остальное\Python\Steam\start.py", line 111, in <module>
    confirm_listing(steam_client)
  File "C:\Users\win\OneDrive\Рабочий стол\Остальное\Python\Steam\start.py", line 105, in confirm_listing
    confirmations = steam_client.confirmations.get_confirmations()
  File "C:\Users\win\OneDrive\Рабочий стол\Остальное\Python\Steam\steamcom\utils.py", line 21, in func_wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\win\OneDrive\Рабочий стол\Остальное\Python\Steam\steamcom\confirmations.py", line 60, in get_confirmations
    for conf in confirmations_page['conf']:
KeyError: 'conf'

My code:

```
def confirm_listing(steam_client):
    confirmations = steam_client.confirmations.get_confirmations()
    print(confirmations)  # [Confirmation: Sell - IDF, Confirmation: Sell - SWAT]
    steam_client.confirmations.allow_all_confirmations([ConfirmationType.CREATE_LISTING])
    print('Listings confirmed')
```

**Comment by LinarSharifullin** [comment]
I don't have such a mistake, I think you have time constraints

**Comment by camillo1990** [comment]
I found a bug, the error appears when restoring a session via Pickle. If you use load_session(extracted_session) then the error appears:
`Traceback (most recent call last):
  File "C:\Users\win\OneDrive\Рабочий стол\test.py", line 38, in <module>
    steam_client.load_session(extracted_session1)
  File "C:\Users\win\OneDrive\Рабочий стол\steamcom\client.py", line 77, in load_session
    raise SessionIsInvalid()
steamcom.exceptions.SessionIsInvalid`

**Comment by LinarSharifullin** [comment]
There really is such a thing, you need to get a new session if this error occurs. The authentication logic has changed a little on steam, cookies expire quickly, which need to be updated with a refresh token. I'm going to implement this too
